// Sandbox/demo-nuxtjs/app.vue
<template>
    <div>
        <button @click="initSciChart()">Show Sci Chart</button>

        <div
            id="scichart-root"
            style="width: 600px; height: 400px; margin: auto"
        />
    </div>
</template>

<script>
import * as SciChart from "scichart";

export default {
    name: "index",
    mounted() {
        console.log("onMounted");
    },
    methods: {
        async initSciChart() {
            // Create the SciChartSurface in the div 'scichart-root'
            // The SciChartSurface, and webassembly context 'wasmContext' are paired. This wasmContext
            // instance must be passed to other types that exist on the same surface.
            const { sciChartSurface, wasmContext } =
                await SciChart.SciChartSurface.create("scichart-root");

            const {
                NumericAxis,
                XyDataSeries,
                ZoomExtentsModifier,
                ZoomPanModifier,
                MouseWheelZoomModifier,
                RolloverModifier,
                FastLineRenderableSeries,
            } = SciChart;

            // Create an X,Y Axis and add to the chart
            const xAxis = new NumericAxis(wasmContext);
            const yAxis = new NumericAxis(wasmContext);
            sciChartSurface.xAxes.add(xAxis);
            sciChartSurface.yAxes.add(yAxis);

            // Declare a DataSeries
            const xyDataSeries = new XyDataSeries(wasmContext);

            function getRandonInt(max) {
                return Math.floor(Math.random() * max);
            }
            const xValues = [];
            const yValues = [];

            for (let index = 0; index < 100; index++) {
                xValues.push(index);
                yValues.push(getRandonInt(50));
            }

            xyDataSeries.appendRange(xValues, yValues);

            // Add Chart Modifiers
            sciChartSurface.chartModifiers.add(
                new ZoomExtentsModifier(),
                new ZoomPanModifier(),
                new MouseWheelZoomModifier(),
                new RolloverModifier({ rolloverLineStroke: "rgba(255,0,0,1)" })
            );

            // Add a line series to the SciChartSurface
            const lineSeries = new FastLineRenderableSeries(wasmContext);
            lineSeries.strokeThickness = 3;
            lineSeries.stroke = "rgba(255,0,0,1)";
            lineSeries.dataSeries = xyDataSeries;

            sciChartSurface.renderableSeries.add(lineSeries);
        },
    },
};
</script>

// Sandbox/demo-react-scichart/src/App.js
import React, { useEffect } from "react";
import { SciChartSurface, NumericAxis } from "scichart";

async function initSciChart() {
  // LICENSING //
  // Set your license code here
  // You can get a trial license key from https://www.scichart.com/licensing-scichart-js/
  // Purchased license keys can be viewed at https://www.scichart.com/profile
  //
  // e.g.
  //
  // SciChartSurface.setRuntimeLicenseKey("YOUR_RUNTIME_KEY");
  //
  // Also, once activated (trial or paid license) having the licensing wizard open on your machine
  // will mean any or all applications you run locally will be fully licensed.

  // Create the SciChartSurface in the div 'scichart-root'
  // The SciChartSurface, and webassembly context 'wasmContext' are paired. This wasmContext
  // instance must be passed to other types that exist on the same surface.
  const { sciChartSurface, wasmContext } = await SciChartSurface.create(
    "scichart-root"
  );

  // Create an X,Y Axis and add to the chart
  const xAxis = new NumericAxis(wasmContext);
  const yAxis = new NumericAxis(wasmContext);

  sciChartSurface.xAxes.add(xAxis);
  sciChartSurface.yAxes.add(yAxis);

  // That's it! You just created your first SciChartSurface!
}

function App() {
  useEffect(() => {
    console.log("use effect");
    initSciChart();
  });

  return (
    <div className="App">
      <header className="App-header">
        <h1>SciChart.js with React hello world!</h1>
        <p>
          In this example we setup webpack, scichart, react and create a simple
          chart with one X and Y axis
        </p>
      </header>
      <div id="scichart-root" style={{ maxWidth: 900 }} />
    </div>
  );
}

export default App;
